name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      # Greeting for first interaction
      - name: First Interaction Greeting
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "🎉 Welcome to our project! Thank you for contributing. We're glad to have you here. Feel free to ask any questions or raise any concerns you might have. Happy coding! 🚀"
          pr-message: "🎉 Thanks for making your first pull request! We appreciate your efforts to contribute. Someone from the team will review it soon. Keep contributing! 🚀"

      
      - name: Label first interaction
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
